ALTER TABLE compras
  ADD COLUMN tipo_dte VARCHAR(2) NULL AFTER estado,
  ADD COLUMN numero_control VARCHAR(31) NULL AFTER tipo_dte,
  ADD COLUMN codigo_generacion VARCHAR(36) NULL AFTER numero_control,
  ADD COLUMN sello_recepcion VARCHAR(100) NULL AFTER codigo_generacion,
  ADD COLUMN numero_factura VARCHAR(100) NULL AFTER sello_recepcion,
  ADD COLUMN referencia_contable VARCHAR(30) NULL AFTER numero_factura,
  ADD COLUMN fecha_emision DATE NULL AFTER referencia_contable,
  ADD COLUMN fecha_recepcion DATE NULL AFTER fecha_emision,
  ADD COLUMN fecha_registro DATE NULL AFTER fecha_recepcion,
  ADD COLUMN total_gravado DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN total_exento DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN total_no_sujeto DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN total_xcomprobar DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN suma_operaciones DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN descuento_global_gravado DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN descuento_global_exento DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN descuento_global_no_sujeto DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN porcentaje_descuento DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN total_descuento DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN sub_total DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN iva DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN iva_retenido DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN iva_percibido DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN retencion_renta DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN monto_total_operacion DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN total_cargos_no_afectos DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN total_pagar DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN valor_en_letras VARCHAR(300) NULL,
  ADD COLUMN condicion_operacion TINYINT NULL DEFAULT 1,
  ADD COLUMN plazo_tipo VARCHAR(2) NULL,
  ADD COLUMN plazo_periodo INT NULL,
  ADD COLUMN fecha_vencimiento_pago DATE NULL;
